#!/usr/bin/env python3
"""
Verify fragments generated by prepare_fragments.py
Usage: python3 verify_fragments.py <prefix>
"""
import sys
import subprocess
import os
import tempfile
import shutil

def decompress_fragment(frag_data, dest_dir):
    if os.path.exists(dest_dir):
        shutil.rmtree(dest_dir)
    os.makedirs(dest_dir)
    r = subprocess.run(['lz4', '-d', '-c', '/dev/stdin'], input=frag_data, capture_output=True)
    if r.returncode != 0:
        print(f"  lz4 decompress failed: {r.stderr[:200]}")
        return False
    p = subprocess.run(['cpio', '-idm'], input=r.stdout, capture_output=True, cwd=dest_dir)
    if p.returncode != 0:
        print(f"  cpio extract failed: {p.stderr[:200]}")
        return False
    return True

def verify_f0(frag_path):
    print(f"\n=== Verifying F0: {frag_path} ===")
    data = open(frag_path, 'rb').read()
    tmpdir = tempfile.mkdtemp()
    try:
        if not decompress_fragment(data, os.path.join(tmpdir, 'f0')):
            return False
        
        f0_root = os.path.join(tmpdir, 'f0')
        
        # Check critical files
        checks = [
            ('system/lib64/twrp16', 'twrp16 libs directory', True),
            ('system/lib64/twrp16/libbase.so', 'libbase.so', True),
            ('system/lib64/twrp16/libc++.so', 'libc++.so', True),
            ('system/lib64/twrp16/liblog.so', 'liblog.so', True),
            ('system/lib64/twrp16/libcutils.so', 'libcutils.so', True),
            ('system/lib64/twrp16/libutils.so', 'libutils.so', True),
            ('system/lib64/twrp16/libfs_mgr.so', 'libfs_mgr.so', True),
            ('system/lib64/twrp16/liblp.so', 'liblp.so', True),
            ('system/lib64/twrp16/libbootloader_message.so', 'libbootloader_message.so', True),
            ('system/lib64/twrp16/libprotobuf-cpp-lite.so', 'libprotobuf-cpp-lite.so', True),
            ('system/etc/init/hw/init.rc', 'init.rc with setenv', True),
            ('system/bin/recovery', 'recovery binary (should NOT exist)', False),
            ('res', 'res directory (should NOT exist)', False),
        ]
        
        all_ok = True
        for path, desc, should_exist in checks:
            full = os.path.join(f0_root, path)
            exists = os.path.exists(full)
            if should_exist and not exists:
                print(f"  ❌ MISSING: {desc} ({path})")
                all_ok = False
            elif not should_exist and exists:
                print(f"  ❌ SHOULD BE REMOVED: {desc} ({path})")
                all_ok = False
            elif should_exist and exists:
                size = os.path.getsize(full)
                print(f"  ✅ {desc}: {size} bytes")
            else:
                print(f"  ✅ Correctly removed: {desc}")
        
        # Check init.rc for LD_LIBRARY_PATH
        init_rc = os.path.join(f0_root, 'system/etc/init/hw/init.rc')
        if os.path.exists(init_rc):
            with open(init_rc) as f:
                content = f.read()
            if 'LD_LIBRARY_PATH' in content and '/system/lib64/twrp16' in content:
                print(f"  ✅ init.rc has LD_LIBRARY_PATH setenv")
            else:
                print(f"  ❌ init.rc missing LD_LIBRARY_PATH setenv")
                all_ok = False
        
        return all_ok
    finally:
        shutil.rmtree(tmpdir, ignore_errors=True)

def verify_f1(frag_path):
    print(f"\n=== Verifying F1: {frag_path} ===")
    data = open(frag_path, 'rb').read()
    tmpdir = tempfile.mkdtemp()
    try:
        if not decompress_fragment(data, os.path.join(tmpdir, 'f1')):
            return False
        
        f1_root = os.path.join(tmpdir, 'f1')
        
        checks = [
            ('system/bin/recovery', 'recovery binary', True),
            ('init.recovery.mt6991.rc', 'mt6991 RC overlay', True),
            ('init.recovery.project.rc', 'project RC overlay', True),
            ('system/lib64/libc.so', 'libc.so', True),
            ('system/lib64/libtwrpmtp-ffs.so', 'TWRP MTP lib', True),
        ]
        
        all_ok = True
        for path, desc, should_exist in checks:
            full = os.path.join(f1_root, path)
            exists = os.path.exists(full)
            if should_exist and not exists:
                print(f"  ❌ MISSING: {desc} ({path})")
                all_ok = False
            elif should_exist and exists:
                size = os.path.getsize(full)
                print(f"  ✅ {desc}: {size} bytes")
            else:
                print(f"  ✅ Correctly absent: {desc}")
        
        return all_ok
    finally:
        shutil.rmtree(tmpdir, ignore_errors=True)

def main():
    if len(sys.argv) < 2:
        print("Usage: python3 verify_fragments.py <prefix>")
        print("  e.g., python3 verify_fragments.py /tmp/fragments")
        sys.exit(1)
    
    prefix = sys.argv[1]
    f0 = f"{prefix}.f0.lz4"
    f1 = f"{prefix}.f1.lz4"
    
    if not os.path.exists(f0):
        print(f"F0 not found: {f0}")
        sys.exit(1)
    if not os.path.exists(f1):
        print(f"F1 not found: {f1}")
        sys.exit(1)
    
    ok = True
    ok &= verify_f0(f0)
    ok &= verify_f1(f1)
    
    print(f"\n{'='*40}")
    if ok:
        print("✅ ALL CHECKS PASSED - Fragments look good!")
    else:
        print("❌ SOME CHECKS FAILED - Review output above")
    print(f"{'='*40}")
    
    sys.exit(0 if ok else 1)

if __name__ == '__main__':
    main()